//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumericalCalculator.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumericalCalculator.Translations.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutForm_AboutForm {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Calculator.
        /// </summary>
        public static string AboutForm_lblAppTitle {
            get {
                return ResourceManager.GetString("AboutForm_lblAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutForm_lblVersion {
            get {
                return ResourceManager.GetString("AboutForm_lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Calculator.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string AveragesForm_AveragesForm {
            get {
                return ResourceManager.GetString("AveragesForm_AveragesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect fourth argument!.
        /// </summary>
        public static string BesseleFourthArgumentException {
            get {
                return ResourceManager.GetString("BesseleFourthArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect second argument!.
        /// </summary>
        public static string BesseleSecondArgumentException {
            get {
                return ResourceManager.GetString("BesseleSecondArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect third argument!.
        /// </summary>
        public static string BesseleThirdArgumentException {
            get {
                return ResourceManager.GetString("BesseleThirdArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect first argument!.
        /// </summary>
        public static string BesselFirstArgumentException {
            get {
                return ResourceManager.GetString("BesselFirstArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string btnCompute {
            get {
                return ResourceManager.GetString("btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string btnDraw {
            get {
                return ResourceManager.GetString("btnDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential equation.
        /// </summary>
        public static string chkDifferential {
            get {
                return ResourceManager.GetString("chkDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential second-order.
        /// </summary>
        public static string chkDifferentialII {
            get {
                return ResourceManager.GetString("chkDifferentialII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First derivative.
        /// </summary>
        public static string chkFirstDerivative {
            get {
                return ResourceManager.GetString("chkFirstDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string chkFunction {
            get {
                return ResourceManager.GetString("chkFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic scaling.
        /// </summary>
        public static string chkRescaling {
            get {
                return ResourceManager.GetString("chkRescaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second derivative.
        /// </summary>
        public static string chkSecondDerivative {
            get {
                return ResourceManager.GetString("chkSecondDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special function.
        /// </summary>
        public static string chkSpecialFunction {
            get {
                return ResourceManager.GetString("chkSpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string contextMenuStrip_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("contextMenuStrip_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string contextMenuStrip_saveToFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("contextMenuStrip_saveToFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as TXT.
        /// </summary>
        public static string contextMenuStrip_saveToTXTToolStripMenuItem {
            get {
                return ResourceManager.GetString("contextMenuStrip_saveToTXTToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The x coordinates can&apos;t be the same!.
        /// </summary>
        public static string CoordinatesXException {
            get {
                return ResourceManager.GetString("CoordinatesXException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The y coordinates can&apos;t be the same!.
        /// </summary>
        public static string CoordinatesYException {
            get {
                return ResourceManager.GetString("CoordinatesYException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect cut-off value!.
        /// </summary>
        public static string CutoffValueException {
            get {
                return ResourceManager.GetString("CutoffValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the function!.
        /// </summary>
        public static string EmptyFunctionStringException {
            get {
                return ResourceManager.GetString("EmptyFunctionStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured! Checked entered formula!.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illega character:.
        /// </summary>
        public static string ForbiddenSignDetectedException {
            get {
                return ResourceManager.GetString("ForbiddenSignDetectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale change error!.
        /// </summary>
        public static string Form1_MouseWheel_DefaultException {
            get {
                return ResourceManager.GetString("Form1_MouseWheel_DefaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect &quot;from&quot; point!.
        /// </summary>
        public static string FromConversionException {
            get {
                return ResourceManager.GetString("FromConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect x point in first condition!.
        /// </summary>
        public static string FromConversionException_Differential {
            get {
                return ResourceManager.GetString("FromConversionException_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect lower limit of the integration!.
        /// </summary>
        public static string FromConversionException_Integral {
            get {
                return ResourceManager.GetString("FromConversionException_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect point in second condition!.
        /// </summary>
        public static string FromIIConversionException {
            get {
                return ResourceManager.GetString("FromIIConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string FunctionForm_FunctionForm {
            get {
                return ResourceManager.GetString("FunctionForm_FunctionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine = sin
        ///Hyperbolic sine = sinh
        ///Cosine = cos
        ///Hyperbolic cosine = cosh
        ///Tangent = tg, tan
        ///Hyperbolic tangent = tgh, tanh
        ///Cotangent = ctg, ctn, cot
        ///Hyperbolic cotangent = ctgh, ctnh, coth
        ///Secant = sec
        ///Cosecant = csc
        ///Arcsine = asin
        ///Arccosine = acos
        ///Arctangent = atg
        ///Arccotangent = actg
        ///Exponential function with e base = exp
        ///Square root = sqrt
        ///Base 2 logarithm = lg
        ///Base e logarithm = ln
        ///Base 10 logarithm = log
        ///
        ///Factorial of natural numbers less then 20 is computed with standard formula:
        ///5!  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FunctionForm_lblBody {
            get {
                return ResourceManager.GetString("FunctionForm_lblBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use following functions:.
        /// </summary>
        public static string FunctionForm_lblHeader {
            get {
                return ResourceManager.GetString("FunctionForm_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators:  +, -, *, /, ^, !.
        /// </summary>
        public static string FunctionForm_lblOperators {
            get {
                return ResourceManager.GetString("FunctionForm_lblOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the function!.
        /// </summary>
        public static string FunctionNullReferenceException {
            get {
                return ResourceManager.GetString("FunctionNullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the computation!.
        /// </summary>
        public static string FunctionNullReferenceException_Calculator {
            get {
                return ResourceManager.GetString("FunctionNullReferenceException_Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string gbConditions {
            get {
                return ResourceManager.GetString("gbConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits.
        /// </summary>
        public static string gbConditions_Range {
            get {
                return ResourceManager.GetString("gbConditions_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string gbConditionsII {
            get {
                return ResourceManager.GetString("gbConditionsII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string gbDrawFunction {
            get {
                return ResourceManager.GetString("gbDrawFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string gbFunction {
            get {
                return ResourceManager.GetString("gbFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special function.
        /// </summary>
        public static string gbFunction_SpecialFunction {
            get {
                return ResourceManager.GetString("gbFunction_SpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string gbOperation {
            get {
                return ResourceManager.GetString("gbOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string gbPoint {
            get {
                return ResourceManager.GetString("gbPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string gbResult {
            get {
                return ResourceManager.GetString("gbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string gbScale {
            get {
                return ResourceManager.GetString("gbScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect occurance of the E operator!.
        /// </summary>
        public static string IncorrectEOperatorOccurrenceException {
            get {
                return ResourceManager.GetString("IncorrectEOperatorOccurrenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity limit is not supported.
        /// </summary>
        public static string IntegralInfinityRangeNotSupportedException {
            get {
                return ResourceManager.GetString("IntegralInfinityRangeNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation and approximation.
        /// </summary>
        public static string interpolationApproximationToolStripMenuItem {
            get {
                return ResourceManager.GetString("interpolationApproximationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string InterpolationForm_btnApply {
            get {
                return ResourceManager.GetString("InterpolationForm_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string InterpolationForm_btnCompute {
            get {
                return ResourceManager.GetString("InterpolationForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect values in some cells!.
        /// </summary>
        public static string InterpolationForm_FormatException {
            get {
                return ResourceManager.GetString("InterpolationForm_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation.
        /// </summary>
        public static string InterpolationForm_gbApproximation {
            get {
                return ResourceManager.GetString("InterpolationForm_gbApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation.
        /// </summary>
        public static string InterpolationForm_gbInterpolation {
            get {
                return ResourceManager.GetString("InterpolationForm_gbInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t approximate function. Try other level of approximation..
        /// </summary>
        public static string InterpolationForm_InconsistentSystemOfEquationsException {
            get {
                return ResourceManager.GetString("InterpolationForm_InconsistentSystemOfEquationsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation.
        /// </summary>
        public static string InterpolationForm_InterpolationForm {
            get {
                return ResourceManager.GetString("InterpolationForm_InterpolationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string InterpolationForm_lblApproximationLevel {
            get {
                return ResourceManager.GetString("InterpolationForm_lblApproximationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run interpolation or approximation first..
        /// </summary>
        public static string InterpolationForm_MessageBox_btnApply {
            get {
                return ResourceManager.GetString("InterpolationForm_MessageBox_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No points were provided!.
        /// </summary>
        public static string InterpolationForm_NoPointsProvidedException {
            get {
                return ResourceManager.GetString("InterpolationForm_NoPointsProvidedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide values for all cells!.
        /// </summary>
        public static string InterpolationForm_NullReferenceException {
            get {
                return ResourceManager.GetString("InterpolationForm_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation.
        /// </summary>
        public static string InterpolationForm_rbApproximation {
            get {
                return ResourceManager.GetString("InterpolationForm_rbApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagrange interpolation.
        /// </summary>
        public static string InterpolationForm_rbInterpolation {
            get {
                return ResourceManager.GetString("InterpolationForm_rbInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong approximation level - expected greater than zero!.
        /// </summary>
        public static string InterpolationForm_WrongApproximationLevelException {
            get {
                return ResourceManager.GetString("InterpolationForm_WrongApproximationLevelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation time:.
        /// </summary>
        public static string lblCalculationTime {
            get {
                return ResourceManager.GetString("lblCalculationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut-off threshold:.
        /// </summary>
        public static string lblCutoff {
            get {
                return ResourceManager.GetString("lblCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower.
        /// </summary>
        public static string lblFrom_Range {
            get {
                return ResourceManager.GetString("lblFrom_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling:.
        /// </summary>
        public static string lblSampling {
            get {
                return ResourceManager.GetString("lblSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upper.
        /// </summary>
        public static string lblTo_Range {
            get {
                return ResourceManager.GetString("lblTo_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left and right brackets amount does not match!.
        /// </summary>
        public static string LeftAndRightBracketsAmountDoesNotMatchException {
            get {
                return ResourceManager.GetString("LeftAndRightBracketsAmountDoesNotMatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect values in some cells!.
        /// </summary>
        public static string LinearEquation_FormatException {
            get {
                return ResourceManager.GetString("LinearEquation_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide value for all cells!.
        /// </summary>
        public static string LinearEquation_NullReferenceException {
            get {
                return ResourceManager.GetString("LinearEquation_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string LinearEquationForm_btnCompute {
            get {
                return ResourceManager.GetString("LinearEquationForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of variables:.
        /// </summary>
        public static string LinearEquationForm_lblNumberOfVariables {
            get {
                return ResourceManager.GetString("LinearEquationForm_lblNumberOfVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string LinearEquationForm_lblResults {
            get {
                return ResourceManager.GetString("LinearEquationForm_lblResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear equation.
        /// </summary>
        public static string LinearEquationForm_LinearEquationForm {
            get {
                return ResourceManager.GetString("LinearEquationForm_LinearEquationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string MeanForm_btnCompute {
            get {
                return ResourceManager.GetString("MeanForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string MeanForm_dgvValues_Value {
            get {
                return ResourceManager.GetString("MeanForm_dgvValues_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string MeanForm_dgvValues_Weight {
            get {
                return ResourceManager.GetString("MeanForm_dgvValues_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect values in some cells!.
        /// </summary>
        public static string MeanForm_FormatException {
            get {
                return ResourceManager.GetString("MeanForm_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string MeanForm_gbResult {
            get {
                return ResourceManager.GetString("MeanForm_gbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MeanForm_gbType {
            get {
                return ResourceManager.GetString("MeanForm_gbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No values provided!.
        /// </summary>
        public static string MeanForm_NoValuesProvidedException {
            get {
                return ResourceManager.GetString("MeanForm_NoValuesProvidedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide values for all cells!.
        /// </summary>
        public static string MeanForm_NullReferenceException {
            get {
                return ResourceManager.GetString("MeanForm_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic.
        /// </summary>
        public static string MeanForm_rbArithmetic {
            get {
                return ResourceManager.GetString("MeanForm_rbArithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted.
        /// </summary>
        public static string MeanForm_rbWeighted {
            get {
                return ResourceManager.GetString("MeanForm_rbWeighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string menuStrip_aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Application.
        /// </summary>
        public static string menuStrip_applicationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_applicationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string menuStrip_closeToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_closeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extra computations.
        /// </summary>
        public static string menuStrip_extraComputationsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_extraComputationsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string menuStrip_fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Functions.
        /// </summary>
        public static string menuStrip_functionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_functionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart preview while moving it.
        /// </summary>
        public static string menuStrip_graphPreviewWhileMovingToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_graphPreviewWhileMovingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart _preview while window scaling.
        /// </summary>
        public static string menuStrip_graphPreviewWhileWindowsScalingToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_graphPreviewWhileWindowsScalingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Chart.
        /// </summary>
        public static string menuStrip_graphToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_graphToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Interpolation and approximation.
        /// </summary>
        public static string menuStrip_interpolationApproximationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_interpolationApproximationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string menuStrip_languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Linear equations.
        /// </summary>
        public static string menuStrip_linearEquationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_linearEquationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mean.
        /// </summary>
        public static string menuStrip_meanToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_meanToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Multiple integral.
        /// </summary>
        public static string menuStrip_multipleIntegralToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_multipleIntegralToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string menuStrip_optionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_optionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Proportions.
        /// </summary>
        public static string menuStrip_proportionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_proportionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Special Function in Operation section and insert x variable as one of its arguments..
        /// </summary>
        public static string MessageBox_btnSpecialFunction_Click {
            get {
                return ResourceManager.GetString("MessageBox_btnSpecialFunction_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string MessageBox_btnSpecialFunction_Click_Caption {
            get {
                return ResourceManager.GetString("MessageBox_btnSpecialFunction_Click_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string MessageBox_Caption_Error {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string MessageBox_Caption_Warning {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error drawing graph grid!.
        /// </summary>
        public static string MessageBox_ClearGraph_Exception {
            get {
                return ResourceManager.GetString("MessageBox_ClearGraph_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy image to clipboard!.
        /// </summary>
        public static string MessageBox_CopyToClipboard_Failure {
            get {
                return ResourceManager.GetString("MessageBox_CopyToClipboard_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image copied to clipboard successfully!.
        /// </summary>
        public static string MessageBox_CopyToClipboard_Success {
            get {
                return ResourceManager.GetString("MessageBox_CopyToClipboard_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E was interpreted as Euler&apos;s number!.
        /// </summary>
        public static string MessageBox_EulerWarning {
            get {
                return ResourceManager.GetString("MessageBox_EulerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application installation is corrupted! It may run unstable. You should reinstall this application..
        /// </summary>
        public static string MessageBox_InstallationCorrupted {
            get {
                return ResourceManager.GetString("MessageBox_InstallationCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidentified problem!.
        /// </summary>
        public static string MessageBox_InstallationCorrupted_Caption {
            get {
                return ResourceManager.GetString("MessageBox_InstallationCorrupted_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the file!.
        /// </summary>
        public static string MessageBox_SaveToFile_Failure {
            get {
                return ResourceManager.GetString("MessageBox_SaveToFile_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully!.
        /// </summary>
        public static string MessageBox_SaveToFile_Success {
            get {
                return ResourceManager.GetString("MessageBox_SaveToFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the file!.
        /// </summary>
        public static string MessageBox_SaveToTXT_Failure {
            get {
                return ResourceManager.GetString("MessageBox_SaveToTXT_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of graph points!.
        /// </summary>
        public static string MessageBox_SaveToTXT_Failure_LackPoints {
            get {
                return ResourceManager.GetString("MessageBox_SaveToTXT_Failure_LackPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully!.
        /// </summary>
        public static string MessageBox_SaveToTXT_Success {
            get {
                return ResourceManager.GetString("MessageBox_SaveToTXT_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no solutions in the real numbers set!.
        /// </summary>
        public static string NaNOccuredException {
            get {
                return ResourceManager.GetString("NaNOccuredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one graph option..
        /// </summary>
        public static string NoneGraphOptionCheckedException {
            get {
                return ResourceManager.GetString("NoneGraphOptionCheckedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None or few roots on given interval.
        /// </summary>
        public static string NoneOrFewRootsOnGivenIntervalException {
            get {
                return ResourceManager.GetString("NoneOrFewRootsOnGivenIntervalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurred at the beginning of the expression!.
        /// </summary>
        public static string OperatorAtTheBeginningOfTheExpressionException {
            get {
                return ResourceManager.GetString("OperatorAtTheBeginningOfTheExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurred at the end of the expression!.
        /// </summary>
        public static string OperatorAtTheEndOfTheExpressionException {
            get {
                return ResourceManager.GetString("OperatorAtTheEndOfTheExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t draw this function in this interval..
        /// </summary>
        public static string OverflowException {
            get {
                return ResourceManager.GetString("OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect X and Y values!.
        /// </summary>
        public static string picGraph_MouseUp_CoordinatesException {
            get {
                return ResourceManager.GetString("picGraph_MouseUp_CoordinatesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect point!.
        /// </summary>
        public static string PointConversionException {
            get {
                return ResourceManager.GetString("PointConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string ProportionsForm_btnCompute {
            get {
                return ResourceManager.GetString("ProportionsForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ProportionsForm_gbResult {
            get {
                return ResourceManager.GetString("ProportionsForm_gbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string ProportionsForm_gbValues {
            get {
                return ResourceManager.GetString("ProportionsForm_gbValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put x only in one field you want to compute:.
        /// </summary>
        public static string ProportionsForm_lblDescription {
            get {
                return ResourceManager.GetString("ProportionsForm_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportions.
        /// </summary>
        public static string ProportionsForm_ProportionsForm {
            get {
                return ResourceManager.GetString("ProportionsForm_ProportionsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value in first field!.
        /// </summary>
        public static string ProportionsForm_V1FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V1FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value in second field!.
        /// </summary>
        public static string ProportionsForm_V2FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V2FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value in thrid field!.
        /// </summary>
        public static string ProportionsForm_V3FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V3FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value in fourth field!.
        /// </summary>
        public static string ProportionsForm_V4FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V4FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string rbCalculator {
            get {
                return ResourceManager.GetString("rbCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First derivative.
        /// </summary>
        public static string rbDerivativePoint {
            get {
                return ResourceManager.GetString("rbDerivativePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second derivative.
        /// </summary>
        public static string rbDerivativePointBis {
            get {
                return ResourceManager.GetString("rbDerivativePointBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential equation.
        /// </summary>
        public static string rbDifferential {
            get {
                return ResourceManager.GetString("rbDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential second-order.
        /// </summary>
        public static string rbDifferentialII {
            get {
                return ResourceManager.GetString("rbDifferentialII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string rbHybrid {
            get {
                return ResourceManager.GetString("rbHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral.
        /// </summary>
        public static string rbIntegral {
            get {
                return ResourceManager.GetString("rbIntegral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the function at point.
        /// </summary>
        public static string rbPoint {
            get {
                return ResourceManager.GetString("rbPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Root.
        /// </summary>
        public static string rbRoot {
            get {
                return ResourceManager.GetString("rbRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special function.
        /// </summary>
        public static string rbSpecialFunction {
            get {
                return ResourceManager.GetString("rbSpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect sampling value!.
        /// </summary>
        public static string SamplingValueException {
            get {
                return ResourceManager.GetString("SamplingValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string saveFileDialog_FileName {
            get {
                return ResourceManager.GetString("saveFileDialog_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured! Checked entered formula!.
        /// </summary>
        public static string SystemException {
            get {
                return ResourceManager.GetString("SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can be only one variable in the proportion!.
        /// </summary>
        public static string ThereCanBeOnlyOneVariableInProportionException {
            get {
                return ResourceManager.GetString("ThereCanBeOnlyOneVariableInProportionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect &quot;to&quot; point!.
        /// </summary>
        public static string ToConversionException {
            get {
                return ResourceManager.GetString("ToConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value in first condition!.
        /// </summary>
        public static string ToConversionException_Differential {
            get {
                return ResourceManager.GetString("ToConversionException_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect upper limit of integration!.
        /// </summary>
        public static string ToConversionException_Integral {
            get {
                return ResourceManager.GetString("ToConversionException_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value in second condition!.
        /// </summary>
        public static string ToIIConversionException {
            get {
                return ResourceManager.GetString("ToIIConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factorials occurred side by side!.
        /// </summary>
        public static string TwoFactorialsOccuredSideBySideException {
            get {
                return ResourceManager.GetString("TwoFactorialsOccuredSideBySideException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two operators occurred side by side!.
        /// </summary>
        public static string TwoOperatorsOccurredSideBySideException {
            get {
                return ResourceManager.GetString("TwoOperatorsOccurredSideBySideException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can&apos;t be any variables in the computation!.
        /// </summary>
        public static string VariableFoundException {
            get {
                return ResourceManager.GetString("VariableFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable x was not found in the proportion!.
        /// </summary>
        public static string VariableNotFoundException {
            get {
                return ResourceManager.GetString("VariableNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect x-axis &quot;from&quot; value.
        /// </summary>
        public static string xFromException {
            get {
                return ResourceManager.GetString("xFromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect x-axis values. &quot;From&quot; value can&apos;t be greater then (or equal) &quot;to&quot; value..
        /// </summary>
        public static string XFromIsGreaterThenXToException {
            get {
                return ResourceManager.GetString("XFromIsGreaterThenXToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect x-axis &quot;to&quot; value.
        /// </summary>
        public static string xToException {
            get {
                return ResourceManager.GetString("xToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect y-axis &quot;from&quot; value.
        /// </summary>
        public static string yFromException {
            get {
                return ResourceManager.GetString("yFromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect y-axis values. &quot;From&quot; value can&apos;t be greater then (or equal) &quot;to&quot; value..
        /// </summary>
        public static string YFromIsGreaterThenYToException {
            get {
                return ResourceManager.GetString("YFromIsGreaterThenYToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect y-asix &quot;to&quot; value.
        /// </summary>
        public static string yToException {
            get {
                return ResourceManager.GetString("yToException", resourceCulture);
            }
        }
    }
}
