//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumericalCalculator.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguagePolish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguagePolish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumericalCalculator.Translations.LanguagePolish", typeof(LanguagePolish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie.
        /// </summary>
        internal static string AboutForm {
            get {
                return ResourceManager.GetString("AboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Calculator.
        /// </summary>
        internal static string AboutForm_lblAppTitle {
            get {
                return ResourceManager.GetString("AboutForm_lblAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja.
        /// </summary>
        internal static string AboutForm_lblVersion {
            get {
                return ResourceManager.GetString("AboutForm_lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny czwarty argument!.
        /// </summary>
        internal static string BesseleFourthArgumentException {
            get {
                return ResourceManager.GetString("BesseleFourthArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny drugi argument!.
        /// </summary>
        internal static string BesseleSecondArgumentException {
            get {
                return ResourceManager.GetString("BesseleSecondArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny trzeci argument!.
        /// </summary>
        internal static string BesseleThirdArgumentException {
            get {
                return ResourceManager.GetString("BesseleThirdArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny pierwszy argument!.
        /// </summary>
        internal static string BesselFirstArgumentException {
            get {
                return ResourceManager.GetString("BesselFirstArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string btnCompute {
            get {
                return ResourceManager.GetString("btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rysuj.
        /// </summary>
        internal static string btnDraw {
            get {
                return ResourceManager.GetString("btnDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równanie różniczkowe.
        /// </summary>
        internal static string chkDifferential {
            get {
                return ResourceManager.GetString("chkDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R. różniczkowe drugiego rzędu.
        /// </summary>
        internal static string chkDifferentialII {
            get {
                return ResourceManager.GetString("chkDifferentialII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza pochodna.
        /// </summary>
        internal static string chkFirstDerivative {
            get {
                return ResourceManager.GetString("chkFirstDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja.
        /// </summary>
        internal static string chkFunction {
            get {
                return ResourceManager.GetString("chkFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatyczne skalowanie.
        /// </summary>
        internal static string chkRescaling {
            get {
                return ResourceManager.GetString("chkRescaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druga pochodna.
        /// </summary>
        internal static string chkSecondDerivative {
            get {
                return ResourceManager.GetString("chkSecondDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja specjalna.
        /// </summary>
        internal static string chkSpecialFunction {
            get {
                return ResourceManager.GetString("chkSpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany wyjątek. Sprawdź poprawność wprowadzonej formuły!.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt od!.
        /// </summary>
        internal static string FromConversionException {
            get {
                return ResourceManager.GetString("FromConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt x w pierwszym warunku!.
        /// </summary>
        internal static string FromConversionException_Differential {
            get {
                return ResourceManager.GetString("FromConversionException_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna dolna granica całkowania!.
        /// </summary>
        internal static string FromConversionException_Integral {
            get {
                return ResourceManager.GetString("FromConversionException_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt x w drugim warunku!.
        /// </summary>
        internal static string FromIIConversionException {
            get {
                return ResourceManager.GetString("FromIIConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje.
        /// </summary>
        internal static string FunctionForm {
            get {
                return ResourceManager.GetString("FunctionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinus = sin
        ///Sinus hiperboliczny = sinh
        ///Cosinus = cos
        ///Cosinus hiperboliczny = cosh
        ///Tangens = tg, tan
        ///Tangens hiperboliczny = tgh, tanh
        ///Cotangens = ctg, ctn, cot
        ///Cotangens hiperboliczny = ctgh, ctnh, coth
        ///Secans = sec
        ///Cosecans = csc
        ///Arcsin = asin
        ///Arccos = acos
        ///Arctg = atg
        ///Arcctg = actg
        ///Funkcja wykładnicza o podstawie e = exp
        ///Pierwiastek = sqrt
        ///Logarytm o podstawie 2 = lg
        ///Logarytm o podstawie e = ln
        ///Logarytm o podstawie 10 = log
        ///
        ///Silnia z liczb naturalnych mniejszych od 20 jest liczona stan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FunctionForm_lblBody {
            get {
                return ResourceManager.GetString("FunctionForm_lblBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W programie można używać następujących funkcji:.
        /// </summary>
        internal static string FunctionForm_lblHeader {
            get {
                return ResourceManager.GetString("FunctionForm_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatory:  +, -, *, /, ^, !.
        /// </summary>
        internal static string FunctionForm_lblOperators {
            get {
                return ResourceManager.GetString("FunctionForm_lblOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz funkcję!.
        /// </summary>
        internal static string FunctionNullReferenceException {
            get {
                return ResourceManager.GetString("FunctionNullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz działanie!.
        /// </summary>
        internal static string FunctionNullReferenceException_Calculator {
            get {
                return ResourceManager.GetString("FunctionNullReferenceException_Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warunki.
        /// </summary>
        internal static string gbConditions {
            get {
                return ResourceManager.GetString("gbConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granice.
        /// </summary>
        internal static string gbConditions_Range {
            get {
                return ResourceManager.GetString("gbConditions_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warunki.
        /// </summary>
        internal static string gbConditionsII {
            get {
                return ResourceManager.GetString("gbConditionsII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rysuj.
        /// </summary>
        internal static string gbDrawFunction {
            get {
                return ResourceManager.GetString("gbDrawFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja.
        /// </summary>
        internal static string gbFunction {
            get {
                return ResourceManager.GetString("gbFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja specjalna.
        /// </summary>
        internal static string gbFunction_SpecialFunction {
            get {
                return ResourceManager.GetString("gbFunction_SpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja.
        /// </summary>
        internal static string gbOperation {
            get {
                return ResourceManager.GetString("gbOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkt.
        /// </summary>
        internal static string gbPoint {
            get {
                return ResourceManager.GetString("gbPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        internal static string gbResult {
            get {
                return ResourceManager.GetString("gbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skala.
        /// </summary>
        internal static string gbScale {
            get {
                return ResourceManager.GetString("gbScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja i aproksymacja.
        /// </summary>
        internal static string interpolationApproximationToolStripMenuItem {
            get {
                return ResourceManager.GetString("interpolationApproximationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja.
        /// </summary>
        internal static string InterpolationForm {
            get {
                return ResourceManager.GetString("InterpolationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        internal static string InterpolationForm_btnApply {
            get {
                return ResourceManager.GetString("InterpolationForm_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string InterpolationForm_btnCompute {
            get {
                return ResourceManager.GetString("InterpolationForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aproksymacja.
        /// </summary>
        internal static string InterpolationForm_gbApproximation {
            get {
                return ResourceManager.GetString("InterpolationForm_gbApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja.
        /// </summary>
        internal static string InterpolationForm_gbInterpolation {
            get {
                return ResourceManager.GetString("InterpolationForm_gbInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aproksymacja stopnia.
        /// </summary>
        internal static string InterpolationForm_rbApproximation {
            get {
                return ResourceManager.GetString("InterpolationForm_rbApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja Lagrange&apos;a.
        /// </summary>
        internal static string InterpolationForm_rbInterpolation {
            get {
                return ResourceManager.GetString("InterpolationForm_rbInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas obliczeń:.
        /// </summary>
        internal static string lblCalculationTime {
            get {
                return ResourceManager.GetString("lblCalculationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próg odcięcia:.
        /// </summary>
        internal static string lblCutoff {
            get {
                return ResourceManager.GetString("lblCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dolna.
        /// </summary>
        internal static string lblFrom_Range {
            get {
                return ResourceManager.GetString("lblFrom_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próbkowanie:.
        /// </summary>
        internal static string lblSampling {
            get {
                return ResourceManager.GetString("lblSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to górna.
        /// </summary>
        internal static string lblTo_Range {
            get {
                return ResourceManager.GetString("lblTo_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równania liniowe.
        /// </summary>
        internal static string LinearEquationForm {
            get {
                return ResourceManager.GetString("LinearEquationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string LinearEquationForm_btnCompute {
            get {
                return ResourceManager.GetString("LinearEquationForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość zmiennych.
        /// </summary>
        internal static string LinearEquationForm_lblNumberOfVariables {
            get {
                return ResourceManager.GetString("LinearEquationForm_lblNumberOfVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki:.
        /// </summary>
        internal static string LinearEquationForm_lblResults {
            get {
                return ResourceManager.GetString("LinearEquationForm_lblResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;O programie.
        /// </summary>
        internal static string menuStrip_aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;rogram.
        /// </summary>
        internal static string menuStrip_applicationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_applicationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zakończ.
        /// </summary>
        internal static string menuStrip_closeToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_closeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dodatkowe obliczenia.
        /// </summary>
        internal static string menuStrip_extraComputationsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_extraComputationsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Plik.
        /// </summary>
        internal static string menuStrip_fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Funkcje.
        /// </summary>
        internal static string menuStrip_functionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_functionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Podgląd wykresu podczas skalowania okna.
        /// </summary>
        internal static string menuStrip_graphPreviewWhileWindowsScalingToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_graphPreviewWhileWindowsScalingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wykres.
        /// </summary>
        internal static string menuStrip_graphToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_graphToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Interpolacja i aproksymacja.
        /// </summary>
        internal static string menuStrip_interpolationApproximationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_interpolationApproximationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Język.
        /// </summary>
        internal static string menuStrip_languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Równania liniowe.
        /// </summary>
        internal static string menuStrip_linearEquationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_linearEquationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Całka wielokrotna.
        /// </summary>
        internal static string menuStrip_multipleIntegralToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_multipleIntegralToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Opcje.
        /// </summary>
        internal static string menuStrip_optionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_optionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd!.
        /// </summary>
        internal static string MessageBox_Caption_Error {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie!.
        /// </summary>
        internal static string MessageBox_Caption_Warning {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd rysowania siatki wykresu!.
        /// </summary>
        internal static string MessageBox_ClearGraph_Exception {
            get {
                return ResourceManager.GetString("MessageBox_ClearGraph_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zinterpretowano E jako liczbę Eulera!.
        /// </summary>
        internal static string MessageBox_EulerWarning {
            get {
                return ResourceManager.GetString("MessageBox_EulerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalacja programu jest niepoprawna. Program, jeżeli się uruchomi, może działać niestabilnie. Należy odinstalować i zainstalować program ponownie!.
        /// </summary>
        internal static string MessageBox_InstallationCorrupted {
            get {
                return ResourceManager.GetString("MessageBox_InstallationCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezidentyfikowany problem.
        /// </summary>
        internal static string MessageBox_InstallationCorrupted_Caption {
            get {
                return ResourceManager.GetString("MessageBox_InstallationCorrupted_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt!.
        /// </summary>
        internal static string PointConversionException {
            get {
                return ResourceManager.GetString("PointConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulator.
        /// </summary>
        internal static string rbCalculator {
            get {
                return ResourceManager.GetString("rbCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza pochodna.
        /// </summary>
        internal static string rbDerivativePoint {
            get {
                return ResourceManager.GetString("rbDerivativePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druga pochodna.
        /// </summary>
        internal static string rbDerivativePointBis {
            get {
                return ResourceManager.GetString("rbDerivativePointBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równanie różniczkowe.
        /// </summary>
        internal static string rbDifferential {
            get {
                return ResourceManager.GetString("rbDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równanie różniczkowe II rzędu.
        /// </summary>
        internal static string rbDifferentialII {
            get {
                return ResourceManager.GetString("rbDifferentialII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwiastek.
        /// </summary>
        internal static string rbHybrid {
            get {
                return ResourceManager.GetString("rbHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całka.
        /// </summary>
        internal static string rbIntegral {
            get {
                return ResourceManager.GetString("rbIntegral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość funkcji w punkcie.
        /// </summary>
        internal static string rbPoint {
            get {
                return ResourceManager.GetString("rbPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwiastek.
        /// </summary>
        internal static string rbRoot {
            get {
                return ResourceManager.GetString("rbRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje specjalne.
        /// </summary>
        internal static string rbSpecialFunction {
            get {
                return ResourceManager.GetString("rbSpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany wyjątek. Sprawdź poprawność wprowadzonej formuły!.
        /// </summary>
        internal static string SystemException {
            get {
                return ResourceManager.GetString("SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt do!.
        /// </summary>
        internal static string ToConversionException {
            get {
                return ResourceManager.GetString("ToConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w pierwszym warunku!.
        /// </summary>
        internal static string ToConversionException_Differential {
            get {
                return ResourceManager.GetString("ToConversionException_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna górna granica całkowania!.
        /// </summary>
        internal static string ToConversionException_Integral {
            get {
                return ResourceManager.GetString("ToConversionException_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w drugim warunku!.
        /// </summary>
        internal static string ToIIConversionException {
            get {
                return ResourceManager.GetString("ToIIConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W wyr. nie może występować zmienna!.
        /// </summary>
        internal static string VariableFoundException {
            get {
                return ResourceManager.GetString("VariableFoundException", resourceCulture);
            }
        }
    }
}
