//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumericalCalculator.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguagePolish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguagePolish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumericalCalculator.Translations.LanguagePolish", typeof(LanguagePolish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie.
        /// </summary>
        internal static string AboutForm_AboutForm {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Calculator.
        /// </summary>
        internal static string AboutForm_lblAppTitle {
            get {
                return ResourceManager.GetString("AboutForm_lblAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja.
        /// </summary>
        internal static string AboutForm_lblVersion {
            get {
                return ResourceManager.GetString("AboutForm_lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Calculator.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny czwarty argument!.
        /// </summary>
        internal static string BesseleFourthArgumentException {
            get {
                return ResourceManager.GetString("BesseleFourthArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny drugi argument!.
        /// </summary>
        internal static string BesseleSecondArgumentException {
            get {
                return ResourceManager.GetString("BesseleSecondArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny trzeci argument!.
        /// </summary>
        internal static string BesseleThirdArgumentException {
            get {
                return ResourceManager.GetString("BesseleThirdArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny pierwszy argument!.
        /// </summary>
        internal static string BesselFirstArgumentException {
            get {
                return ResourceManager.GetString("BesselFirstArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string btnCompute {
            get {
                return ResourceManager.GetString("btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rysuj.
        /// </summary>
        internal static string btnDraw {
            get {
                return ResourceManager.GetString("btnDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równanie różniczkowe.
        /// </summary>
        internal static string chkDifferential {
            get {
                return ResourceManager.GetString("chkDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R. różniczkowe drugiego rzędu.
        /// </summary>
        internal static string chkDifferentialII {
            get {
                return ResourceManager.GetString("chkDifferentialII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza pochodna.
        /// </summary>
        internal static string chkFirstDerivative {
            get {
                return ResourceManager.GetString("chkFirstDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja.
        /// </summary>
        internal static string chkFunction {
            get {
                return ResourceManager.GetString("chkFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatyczne skalowanie.
        /// </summary>
        internal static string chkRescaling {
            get {
                return ResourceManager.GetString("chkRescaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druga pochodna.
        /// </summary>
        internal static string chkSecondDerivative {
            get {
                return ResourceManager.GetString("chkSecondDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja specjalna.
        /// </summary>
        internal static string chkSpecialFunction {
            get {
                return ResourceManager.GetString("chkSpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj.
        /// </summary>
        internal static string contextMenuStrip_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("contextMenuStrip_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string contextMenuStrip_saveToFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("contextMenuStrip_saveToFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz do TXT.
        /// </summary>
        internal static string contextMenuStrip_saveToTXTToolStripMenuItem {
            get {
                return ResourceManager.GetString("contextMenuStrip_saveToTXTToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wspolrzedne x od i do nie mogą być takie same!.
        /// </summary>
        internal static string CoordinatesXException {
            get {
                return ResourceManager.GetString("CoordinatesXException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wspolrzedne y od i do nie mogą być takie same!.
        /// </summary>
        internal static string CoordinatesYException {
            get {
                return ResourceManager.GetString("CoordinatesYException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawnna wartość filtru!.
        /// </summary>
        internal static string CutoffValueException {
            get {
                return ResourceManager.GetString("CutoffValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz funkcję!.
        /// </summary>
        internal static string EmptyFunctionStringException {
            get {
                return ResourceManager.GetString("EmptyFunctionStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany wyjątek. Sprawdź poprawność wprowadzonej formuły!.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Występuje niedozwolony znak:.
        /// </summary>
        internal static string ForbiddenSignDetectedException {
            get {
                return ResourceManager.GetString("ForbiddenSignDetectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd zmiany skali!.
        /// </summary>
        internal static string Form1_MouseWheel_DefaultException {
            get {
                return ResourceManager.GetString("Form1_MouseWheel_DefaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt od!.
        /// </summary>
        internal static string FromConversionException {
            get {
                return ResourceManager.GetString("FromConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt x w pierwszym warunku!.
        /// </summary>
        internal static string FromConversionException_Differential {
            get {
                return ResourceManager.GetString("FromConversionException_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna dolna granica całkowania!.
        /// </summary>
        internal static string FromConversionException_Integral {
            get {
                return ResourceManager.GetString("FromConversionException_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt x w drugim warunku!.
        /// </summary>
        internal static string FromIIConversionException {
            get {
                return ResourceManager.GetString("FromIIConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje.
        /// </summary>
        internal static string FunctionForm_FunctionForm {
            get {
                return ResourceManager.GetString("FunctionForm_FunctionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinus = sin
        ///Sinus hiperboliczny = sinh
        ///Cosinus = cos
        ///Cosinus hiperboliczny = cosh
        ///Tangens = tg, tan
        ///Tangens hiperboliczny = tgh, tanh
        ///Cotangens = ctg, ctn, cot
        ///Cotangens hiperboliczny = ctgh, ctnh, coth
        ///Secans = sec
        ///Cosecans = csc
        ///Arcsin = asin
        ///Arccos = acos
        ///Arctg = atg
        ///Arcctg = actg
        ///Funkcja wykładnicza o podstawie e = exp
        ///Pierwiastek = sqrt
        ///Logarytm o podstawie 2 = lg
        ///Logarytm o podstawie e = ln
        ///Logarytm o podstawie 10 = log
        ///
        ///Silnia z liczb naturalnych mniejszych od 20 jest liczona stan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FunctionForm_lblBody {
            get {
                return ResourceManager.GetString("FunctionForm_lblBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W programie można używać następujących funkcji:.
        /// </summary>
        internal static string FunctionForm_lblHeader {
            get {
                return ResourceManager.GetString("FunctionForm_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatory:  +, -, *, /, ^, !.
        /// </summary>
        internal static string FunctionForm_lblOperators {
            get {
                return ResourceManager.GetString("FunctionForm_lblOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz funkcję!.
        /// </summary>
        internal static string FunctionNullReferenceException {
            get {
                return ResourceManager.GetString("FunctionNullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz działanie!.
        /// </summary>
        internal static string FunctionNullReferenceException_Calculator {
            get {
                return ResourceManager.GetString("FunctionNullReferenceException_Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warunki.
        /// </summary>
        internal static string gbConditions {
            get {
                return ResourceManager.GetString("gbConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granice.
        /// </summary>
        internal static string gbConditions_Range {
            get {
                return ResourceManager.GetString("gbConditions_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warunki.
        /// </summary>
        internal static string gbConditionsII {
            get {
                return ResourceManager.GetString("gbConditionsII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rysuj.
        /// </summary>
        internal static string gbDrawFunction {
            get {
                return ResourceManager.GetString("gbDrawFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja.
        /// </summary>
        internal static string gbFunction {
            get {
                return ResourceManager.GetString("gbFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja specjalna.
        /// </summary>
        internal static string gbFunction_SpecialFunction {
            get {
                return ResourceManager.GetString("gbFunction_SpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja.
        /// </summary>
        internal static string gbOperation {
            get {
                return ResourceManager.GetString("gbOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkt.
        /// </summary>
        internal static string gbPoint {
            get {
                return ResourceManager.GetString("gbPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        internal static string gbResult {
            get {
                return ResourceManager.GetString("gbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skala.
        /// </summary>
        internal static string gbScale {
            get {
                return ResourceManager.GetString("gbScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne wystąpienie operatora &quot;E&quot;.
        /// </summary>
        internal static string IncorrectEOperatorOccurrenceException {
            get {
                return ResourceManager.GetString("IncorrectEOperatorOccurrenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niestety nieskończoność nie jest jeszcze obsługiwana.
        /// </summary>
        internal static string IntegralInfinityRangeNotSupportedException {
            get {
                return ResourceManager.GetString("IntegralInfinityRangeNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja i aproksymacja.
        /// </summary>
        internal static string interpolationApproximationToolStripMenuItem {
            get {
                return ResourceManager.GetString("interpolationApproximationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        internal static string InterpolationForm_btnApply {
            get {
                return ResourceManager.GetString("InterpolationForm_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string InterpolationForm_btnCompute {
            get {
                return ResourceManager.GetString("InterpolationForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne wartosci w komórkach!.
        /// </summary>
        internal static string InterpolationForm_FormatException {
            get {
                return ResourceManager.GetString("InterpolationForm_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aproksymacja.
        /// </summary>
        internal static string InterpolationForm_gbApproximation {
            get {
                return ResourceManager.GetString("InterpolationForm_gbApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja.
        /// </summary>
        internal static string InterpolationForm_gbInterpolation {
            get {
                return ResourceManager.GetString("InterpolationForm_gbInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie mogę zaproksymować funkcji. Spróbuj aproksymacji innego stopnia..
        /// </summary>
        internal static string InterpolationForm_InconsistentSystemOfEquationsException {
            get {
                return ResourceManager.GetString("InterpolationForm_InconsistentSystemOfEquationsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja.
        /// </summary>
        internal static string InterpolationForm_InterpolationForm {
            get {
                return ResourceManager.GetString("InterpolationForm_InterpolationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpierw zinterpoluj lub zaaproksymuj funkcje..
        /// </summary>
        internal static string InterpolationForm_MessageBox_btnApply {
            get {
                return ResourceManager.GetString("InterpolationForm_MessageBox_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podano żadnych punktów!.
        /// </summary>
        internal static string InterpolationForm_NoPointsProvidedException {
            get {
                return ResourceManager.GetString("InterpolationForm_NoPointsProvidedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wszystkie komorki zostaly wypelnione!.
        /// </summary>
        internal static string InterpolationForm_NullReferenceException {
            get {
                return ResourceManager.GetString("InterpolationForm_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aproksymacja stopnia.
        /// </summary>
        internal static string InterpolationForm_rbApproximation {
            get {
                return ResourceManager.GetString("InterpolationForm_rbApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja Lagrange&apos;a.
        /// </summary>
        internal static string InterpolationForm_rbInterpolation {
            get {
                return ResourceManager.GetString("InterpolationForm_rbInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bledny stopien ekstrapolacji. Oczekiwano stopnia &gt; 0..
        /// </summary>
        internal static string InterpolationForm_WrongApproximationLevelException {
            get {
                return ResourceManager.GetString("InterpolationForm_WrongApproximationLevelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas obliczeń:.
        /// </summary>
        internal static string lblCalculationTime {
            get {
                return ResourceManager.GetString("lblCalculationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próg odcięcia:.
        /// </summary>
        internal static string lblCutoff {
            get {
                return ResourceManager.GetString("lblCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to od.
        /// </summary>
        internal static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dolna.
        /// </summary>
        internal static string lblFrom_Range {
            get {
                return ResourceManager.GetString("lblFrom_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próbkowanie:.
        /// </summary>
        internal static string lblSampling {
            get {
                return ResourceManager.GetString("lblSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        internal static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to górna.
        /// </summary>
        internal static string lblTo_Range {
            get {
                return ResourceManager.GetString("lblTo_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość lewych i prawych nawiasów nie zgadza się!.
        /// </summary>
        internal static string LeftAndRightBracketsAmountDoesNotMatchException {
            get {
                return ResourceManager.GetString("LeftAndRightBracketsAmountDoesNotMatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne wartosci w komórkach!.
        /// </summary>
        internal static string LinearEquation_FormatException {
            get {
                return ResourceManager.GetString("LinearEquation_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wszystkie komorki zostaly wypelnione!.
        /// </summary>
        internal static string LinearEquation_NullReferenceException {
            get {
                return ResourceManager.GetString("LinearEquation_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string LinearEquationForm_btnCompute {
            get {
                return ResourceManager.GetString("LinearEquationForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość zmiennych:.
        /// </summary>
        internal static string LinearEquationForm_lblNumberOfVariables {
            get {
                return ResourceManager.GetString("LinearEquationForm_lblNumberOfVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki:.
        /// </summary>
        internal static string LinearEquationForm_lblResults {
            get {
                return ResourceManager.GetString("LinearEquationForm_lblResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równania liniowe.
        /// </summary>
        internal static string LinearEquationForm_LinearEquationForm {
            get {
                return ResourceManager.GetString("LinearEquationForm_LinearEquationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnie.
        /// </summary>
        internal static string MeanForm_MeanForm {
            get {
                return ResourceManager.GetString("MeanForm_MeanForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;O programie.
        /// </summary>
        internal static string menuStrip_aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;rogram.
        /// </summary>
        internal static string menuStrip_applicationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_applicationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zakończ.
        /// </summary>
        internal static string menuStrip_closeToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_closeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dodatkowe obliczenia.
        /// </summary>
        internal static string menuStrip_extraComputationsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_extraComputationsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Plik.
        /// </summary>
        internal static string menuStrip_fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Funkcje.
        /// </summary>
        internal static string menuStrip_functionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_functionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Podgląd wykresu podczas skalowania okna.
        /// </summary>
        internal static string menuStrip_graphPreviewWhileWindowsScalingToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_graphPreviewWhileWindowsScalingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wykres.
        /// </summary>
        internal static string menuStrip_graphToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_graphToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Interpolacja i aproksymacja.
        /// </summary>
        internal static string menuStrip_interpolationApproximationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_interpolationApproximationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Język.
        /// </summary>
        internal static string menuStrip_languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Równania liniowe.
        /// </summary>
        internal static string menuStrip_linearEquationToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_linearEquationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Śr&amp;ednie.
        /// </summary>
        internal static string menuStrip_meanToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_meanToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Całka wielokrotna.
        /// </summary>
        internal static string menuStrip_multipleIntegralToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_multipleIntegralToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Opcje.
        /// </summary>
        internal static string menuStrip_optionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_optionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporcje.
        /// </summary>
        internal static string menuStrip_proportionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("menuStrip_proportionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystarczy zaznaczyć funkcję specjalną w sekcji wyboru operacji i za jeden z jej argumentów wstawić zmienną x..
        /// </summary>
        internal static string MessageBox_btnSpecialFunction_Click {
            get {
                return ResourceManager.GetString("MessageBox_btnSpecialFunction_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpowiedź.
        /// </summary>
        internal static string MessageBox_btnSpecialFunction_Click_Caption {
            get {
                return ResourceManager.GetString("MessageBox_btnSpecialFunction_Click_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd!.
        /// </summary>
        internal static string MessageBox_Caption_Error {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie!.
        /// </summary>
        internal static string MessageBox_Caption_Warning {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd rysowania siatki wykresu!.
        /// </summary>
        internal static string MessageBox_ClearGraph_Exception {
            get {
                return ResourceManager.GetString("MessageBox_ClearGraph_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się skopiować obrazka do schowka..
        /// </summary>
        internal static string MessageBox_CopyToClipboard_Failure {
            get {
                return ResourceManager.GetString("MessageBox_CopyToClipboard_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrazek skopiowany do schowka..
        /// </summary>
        internal static string MessageBox_CopyToClipboard_Success {
            get {
                return ResourceManager.GetString("MessageBox_CopyToClipboard_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zinterpretowano E jako liczbę Eulera!.
        /// </summary>
        internal static string MessageBox_EulerWarning {
            get {
                return ResourceManager.GetString("MessageBox_EulerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalacja programu jest niepoprawna. Program, jeżeli się uruchomi, może działać niestabilnie. Należy odinstalować i zainstalować program ponownie!.
        /// </summary>
        internal static string MessageBox_InstallationCorrupted {
            get {
                return ResourceManager.GetString("MessageBox_InstallationCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezidentyfikowany problem.
        /// </summary>
        internal static string MessageBox_InstallationCorrupted_Caption {
            get {
                return ResourceManager.GetString("MessageBox_InstallationCorrupted_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zapisać pliku..
        /// </summary>
        internal static string MessageBox_SaveToFile_Failure {
            get {
                return ResourceManager.GetString("MessageBox_SaveToFile_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik zapisany pomyślnie!.
        /// </summary>
        internal static string MessageBox_SaveToFile_Success {
            get {
                return ResourceManager.GetString("MessageBox_SaveToFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zapisać pliku..
        /// </summary>
        internal static string MessageBox_SaveToTXT_Failure {
            get {
                return ResourceManager.GetString("MessageBox_SaveToTXT_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak punktów wykresu!.
        /// </summary>
        internal static string MessageBox_SaveToTXT_Failure_LackPoints {
            get {
                return ResourceManager.GetString("MessageBox_SaveToTXT_Failure_LackPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik zapisany pomyślnie!.
        /// </summary>
        internal static string MessageBox_SaveToTXT_Success {
            get {
                return ResourceManager.GetString("MessageBox_SaveToTXT_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak rozwiązań w zbiorze liczb rzeczywistych!.
        /// </summary>
        internal static string NaNOccuredException {
            get {
                return ResourceManager.GetString("NaNOccuredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano żadnej opcji wykresu!.
        /// </summary>
        internal static string NoneGraphOptionCheckedException {
            get {
                return ResourceManager.GetString("NoneGraphOptionCheckedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak lub kilka pierwiastków na zadanym obszarze.
        /// </summary>
        internal static string NoneOrFewRootsOnGivenIntervalException {
            get {
                return ResourceManager.GetString("NoneOrFewRootsOnGivenIntervalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie może stać na początku wyrażenia!.
        /// </summary>
        internal static string OperatorAtTheBeginningOfTheExpressionException {
            get {
                return ResourceManager.GetString("OperatorAtTheBeginningOfTheExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie może stać na końcu wyrażenia!.
        /// </summary>
        internal static string OperatorAtTheEndOfTheExpressionException {
            get {
                return ResourceManager.GetString("OperatorAtTheEndOfTheExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można narysować tej funkcji w tym przedziale..
        /// </summary>
        internal static string OverflowException {
            get {
                return ResourceManager.GetString("OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne wartości X i Y.
        /// </summary>
        internal static string picGraph_MouseUp_CoordinatesException {
            get {
                return ResourceManager.GetString("picGraph_MouseUp_CoordinatesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt!.
        /// </summary>
        internal static string PointConversionException {
            get {
                return ResourceManager.GetString("PointConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string ProportionsForm_btnCompute {
            get {
                return ResourceManager.GetString("ProportionsForm_btnCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        internal static string ProportionsForm_gbResult {
            get {
                return ResourceManager.GetString("ProportionsForm_gbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości.
        /// </summary>
        internal static string ProportionsForm_gbValues {
            get {
                return ResourceManager.GetString("ProportionsForm_gbValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umieść x w tylko jednym polu:.
        /// </summary>
        internal static string ProportionsForm_lblDescription {
            get {
                return ResourceManager.GetString("ProportionsForm_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporcje.
        /// </summary>
        internal static string ProportionsForm_ProportionsForm {
            get {
                return ResourceManager.GetString("ProportionsForm_ProportionsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w pierwszym polu!.
        /// </summary>
        internal static string ProportionsForm_V1FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V1FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w drugim polu!.
        /// </summary>
        internal static string ProportionsForm_V2FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V2FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w trzecim polu!.
        /// </summary>
        internal static string ProportionsForm_V3FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V3FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w czwartym polu!.
        /// </summary>
        internal static string ProportionsForm_V4FormatException {
            get {
                return ResourceManager.GetString("ProportionsForm_V4FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulator.
        /// </summary>
        internal static string rbCalculator {
            get {
                return ResourceManager.GetString("rbCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza pochodna.
        /// </summary>
        internal static string rbDerivativePoint {
            get {
                return ResourceManager.GetString("rbDerivativePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druga pochodna.
        /// </summary>
        internal static string rbDerivativePointBis {
            get {
                return ResourceManager.GetString("rbDerivativePointBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równanie różniczkowe.
        /// </summary>
        internal static string rbDifferential {
            get {
                return ResourceManager.GetString("rbDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równanie różniczkowe II rzędu.
        /// </summary>
        internal static string rbDifferentialII {
            get {
                return ResourceManager.GetString("rbDifferentialII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwiastek.
        /// </summary>
        internal static string rbHybrid {
            get {
                return ResourceManager.GetString("rbHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całka.
        /// </summary>
        internal static string rbIntegral {
            get {
                return ResourceManager.GetString("rbIntegral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość funkcji w punkcie.
        /// </summary>
        internal static string rbPoint {
            get {
                return ResourceManager.GetString("rbPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwiastek.
        /// </summary>
        internal static string rbRoot {
            get {
                return ResourceManager.GetString("rbRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje specjalne.
        /// </summary>
        internal static string rbSpecialFunction {
            get {
                return ResourceManager.GetString("rbSpecialFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawnna wartość próbkowania!.
        /// </summary>
        internal static string SamplingValueException {
            get {
                return ResourceManager.GetString("SamplingValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string saveFileDialog_FileName {
            get {
                return ResourceManager.GetString("saveFileDialog_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany wyjątek. Sprawdź poprawność wprowadzonej formuły!.
        /// </summary>
        internal static string SystemException {
            get {
                return ResourceManager.GetString("SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W proporcji może być tylko jedna niewiadomoa!.
        /// </summary>
        internal static string ThereCanBeOnlyOneVariableInProportionException {
            get {
                return ResourceManager.GetString("ThereCanBeOnlyOneVariableInProportionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny punkt do!.
        /// </summary>
        internal static string ToConversionException {
            get {
                return ResourceManager.GetString("ToConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w pierwszym warunku!.
        /// </summary>
        internal static string ToConversionException_Differential {
            get {
                return ResourceManager.GetString("ToConversionException_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna górna granica całkowania!.
        /// </summary>
        internal static string ToConversionException_Integral {
            get {
                return ResourceManager.GetString("ToConversionException_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość w drugim warunku!.
        /// </summary>
        internal static string ToIIConversionException {
            get {
                return ResourceManager.GetString("ToIIConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwie silnie występują obok siebie!.
        /// </summary>
        internal static string TwoFactorialsOccuredSideBySideException {
            get {
                return ResourceManager.GetString("TwoFactorialsOccuredSideBySideException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwa operatory występują obok siebie!.
        /// </summary>
        internal static string TwoOperatorsOccurredSideBySideException {
            get {
                return ResourceManager.GetString("TwoOperatorsOccurredSideBySideException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W wyr. nie może występować zmienna!.
        /// </summary>
        internal static string VariableFoundException {
            get {
                return ResourceManager.GetString("VariableFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono zmiennej x w proporcji!.
        /// </summary>
        internal static string VariableNotFoundException {
            get {
                return ResourceManager.GetString("VariableNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość od osi x.
        /// </summary>
        internal static string xFromException {
            get {
                return ResourceManager.GetString("xFromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości skali x są niepoprawne. Wartość początkowa skali nie może być większa (lub równa) od wartości końcowej..
        /// </summary>
        internal static string XFromIsGreaterThenXToException {
            get {
                return ResourceManager.GetString("XFromIsGreaterThenXToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość do osi x.
        /// </summary>
        internal static string xToException {
            get {
                return ResourceManager.GetString("xToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość od osi y.
        /// </summary>
        internal static string yFromException {
            get {
                return ResourceManager.GetString("yFromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości skali y są niepoprawne. Wartość początkowa skali nie może być większa (lub równa) od wartości końcowej..
        /// </summary>
        internal static string YFromIsGreaterThenYToException {
            get {
                return ResourceManager.GetString("YFromIsGreaterThenYToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość do osi y.
        /// </summary>
        internal static string yToException {
            get {
                return ResourceManager.GetString("yToException", resourceCulture);
            }
        }
    }
}
